version: '3'
services:
  server:
    container_name: form-server
    restart: always
    build: ./
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    links:
    - mongo
  mongo:
    container_name: form_mongo
    image: mongo
    ports:
      - "27017:27017"